// רשימות הקודים של משרד החינוך, כפי שהן בתבנית "רישום תלמידים במערכת תלמוד.xls"
// (גיליונות: מדינות מוצא, סוגי אשרות, סוגי לימוד, מילון מושגים). נוצר אוטומטית מהקובץ -
// לא להקליד ידנית. בשמות שבהם הסוגריים בקובץ הפוכים (")בורמה(") - תוקנו.

export interface TalmudCountry { code: number; he: string; en: string }
export const TALMUD_COUNTRIES: TalmudCountry[] = [
  {"code":317,"he":"אבחזיסטאן","en":"ABKHAZISTAN"},
  {"code":254,"he":"אוגנדה","en":"UGANDA"},
  {"code":315,"he":"אוזבקיסטן","en":"UZBEKISTAN"},
  {"code":510,"he":"אוסטריה","en":"AUSTRIA"},
  {"code":860,"he":"אוסטרליה","en":"AUSTRALIA"},
  {"code":305,"he":"אוקראינה","en":"UKRAINE"},
  {"code":820,"he":"אורגוואי","en":"URUGUAY"},
  {"code":741,"he":"אזור תעלת פנמה","en":"CANAL ZONE"},
  {"code":311,"he":"אזרביג'אן","en":"AZERBAIJAN"},
  {"code":670,"he":"איטליה","en":"ITALY"},
  {"code":885,"he":"איי גילברט ואליס","en":"GILBERT  ELLICE ISL"},
  {"code":738,"he":"איי הבתולה","en":"VIRGIN ISLAND"},
  {"code":884,"he":"איי ווליס ופוטונה","en":"WALLIS  FUTUNA ISL"},
  {"code":739,"he":"איי טורקס וקייקוס","en":"TORKAS ISLAND"},
  {"code":864,"he":"איי נורפולק","en":"NORFOLK ISLA"},
  {"code":289,"he":"איי סיישל","en":"SEYCHELLES"},
  {"code":832,"he":"איי פאלקלנד","en":"FALKLAND"},
  {"code":888,"he":"איי פיגי","en":"FIJI"},
  {"code":278,"he":"איי קומורו","en":"COMOROS ISLANDS"},
  {"code":887,"he":"איי קוק","en":"COOK ISL"},
  {"code":733,"he":"איי קיימן","en":"CAYMAN ISLANDS"},
  {"code":219,"he":"איי קייפ וורדה","en":"CAPE VERDE ISLANDS"},
  {"code":861,"he":"איי שלמה הבריטיים","en":"SOLOMON ISLANDS"},
  {"code":130,"he":"אינדונזיה","en":"INDONESIA"},
  {"code":581,"he":"איסלנד","en":"ISLAND"},
  {"code":691,"he":"אירופה לא ידוע","en":"EUROPE UNKNOWN"},
  {"code":600,"he":"אירלנד","en":"IRELAND"},
  {"code":90,"he":"אירן","en":"IRAN"},
  {"code":724,"he":"אל סלבדור","en":"EL SALVADOR"},
  {"code":440,"he":"אלבניה","en":"ALBANIA"},
  {"code":210,"he":"אלגיריה","en":"ALGERIA"},
  {"code":852,"he":"אמריקה לא ידוע","en":"AMERICA UNKNOWN"},
  {"code":281,"he":"אנגולה","en":"ANGOLA"},
  {"code":662,"he":"אנדורה","en":"ANDORRA"},
  {"code":758,"he":"אנטיגואה וברבודה","en":"ANTIGUA AND BARBUDA"},
  {"code":303,"he":"אסטוניה","en":"ESTONIA"},
  {"code":190,"he":"אסיה לא ידוע","en":"ASIA UNKNOWN"},
  {"code":100,"he":"אפגניסטן","en":"AFGHANISTAN"},
  {"code":290,"he":"אפריקה לא ידוע","en":"AFRICA UNKNOWN"},
  {"code":780,"he":"אקואדור","en":"ECUADOR"},
  {"code":830,"he":"ארגנטינה","en":"ARGENTINA"},
  {"code":249,"he":"אריתראה","en":"ERITREA"},
  {"code":9,"he":"ארמניה","en":"ARMENIA"},
  {"code":710,"he":"ארצות הברית","en":"USA"},
  {"code":250,"he":"אתיופיה","en":"ETHIOPIA"},
  {"code":905,"he":"בדרך לארץ","en":"ON WAY TO ISRAEL"},
  {"code":735,"he":"בהמס","en":"BAHAMAS"},
  {"code":115,"he":"בוטן","en":"BHUTAN"},
  {"code":271,"he":"בוטסואנה","en":"BOTSWANA"},
  {"code":420,"he":"בולגריה","en":"BULGARIA"},
  {"code":800,"he":"בוליביה","en":"BOLIVIA"},
  {"code":413,"he":"בוסניה הרצגובינה","en":"BOSNIA  HERZEGOVINA"},
  {"code":285,"he":"בורונדי","en":"BURUNDI"},
  {"code":217,"he":"בורקינה פאסו","en":"BURKINA-FASSO"},
  {"code":61,"he":"בחריין","en":"BAHREIN"},
  {"code":304,"he":"בילורוסיה","en":"BELARUS"},
  {"code":906,"he":"בלב ים","en":"AT SEA"},
  {"code":620,"he":"בלגיה","en":"BELGIUM"},
  {"code":269,"he":"בליז","en":"BELIZE"},
  {"code":116,"he":"בנגלדש","en":"BANGLADESH"},
  {"code":214,"he":"בנין (דהומי)","en":"BENIN (DAHOMEY)"},
  {"code":732,"he":"ברבדוס","en":"BARBADOS"},
  {"code":134,"he":"ברוניי","en":"BRUNEI"},
  {"code":810,"he":"ברזיל","en":"BRAZIL"},
  {"code":300,"he":"ברית המועצות","en":"USSR"},
  {"code":731,"he":"ברמודה","en":"BERMUDA"},
  {"code":216,"he":"גאנה","en":"GHANA"},
  {"code":287,"he":"גבון","en":"GABON"},
  {"code":757,"he":"גואדאלופ","en":"GUADELOUPE"},
  {"code":135,"he":"גואם","en":"GUAM"},
  {"code":726,"he":"גווטאמלה","en":"GUATEMALA"},
  {"code":812,"he":"גויאנה","en":"GUYANA"},
  {"code":811,"he":"גויאנה הצרפתית","en":"GUIANA FR"},
  {"code":251,"he":"גיבוטי","en":"OJIBOUTI"},
  {"code":661,"he":"גיברלטר","en":"GIBRALTAR"},
  {"code":207,"he":"גינאה","en":"GUINEA"},
  {"code":206,"he":"גינאה ביסאו","en":"GUINEA BISSAU"},
  {"code":865,"he":"גינאה החדשה","en":"NEW GUINEA"},
  {"code":288,"he":"גינאה המשוונית","en":"GUINEA EQ"},
  {"code":205,"he":"גמביה","en":"GAMBIA"},
  {"code":737,"he":"גמייקה","en":"JAMAICA"},
  {"code":308,"he":"גרוזיה","en":"GEORGIA"},
  {"code":500,"he":"גרמניה","en":"GERMANY"},
  {"code":502,"he":"גרמניה המזרחית","en":"E GERMANY"},
  {"code":501,"he":"גרמניה המערבית","en":"W GERMANY"},
  {"code":753,"he":"גרנדה","en":"GRENADA"},
  {"code":751,"he":"דומיניקה","en":"DOMINICA"},
  {"code":580,"he":"דנמרק","en":"DENMARK"},
  {"code":850,"he":"דרום אמריקה","en":"SOUTH AMERICA"},
  {"code":270,"he":"דרום אפריקה","en":"S AFRICA"},
  {"code":736,"he":"האיטי","en":"HAITI"},
  {"code":863,"he":"האיים ההברדיים","en":"HEBRIDES"},
  {"code":762,"he":"האנטילים ההולנדים","en":"ANTILLES"},
  {"code":110,"he":"הודו","en":"INDIA"},
  {"code":610,"he":"הולנד","en":"NETHERLANDS"},
  {"code":141,"he":"הונג קונג","en":"HONG KONG"},
  {"code":540,"he":"הונגריה","en":"HUNGARY"},
  {"code":725,"he":"הונדורס","en":"HONDURAS"},
  {"code":590,"he":"הממלכה המאוחדת","en":"UNITED KINGDOM"},
  {"code":734,"he":"הרפ הדומיניקנית","en":"DOMINICAN R"},
  {"code":125,"he":"ויטנאם","en":"VIETNAM"},
  {"code":126,"he":"ויטנאם הדרומית","en":"SOUTH VIETNAM"},
  {"code":760,"he":"ונצואלה","en":"VENEZUELA"},
  {"code":672,"he":"ותיקן","en":"VATICAN"},
  {"code":283,"he":"זאיר","en":"ZAIRE"},
  {"code":259,"he":"זימבאבווה","en":"ZIMBABWE"},
  {"code":261,"he":"זמביה","en":"ZAMBIA"},
  {"code":218,"he":"חוף השנהב","en":"IVORY COAST"},
  {"code":314,"he":"טג'יקיסטאן","en":"TAJIKISTAN"},
  {"code":215,"he":"טוגו","en":"TOGO"},
  {"code":881,"he":"טונגה","en":"TONGA"},
  {"code":133,"he":"טיוון","en":"TAIWAN"},
  {"code":132,"he":"טימור הפורטוגלית","en":"PORTUGUESE TIMOR"},
  {"code":201,"he":"טנגר","en":"TANGIER"},
  {"code":255,"he":"טנזניה","en":"TANZANIA"},
  {"code":761,"he":"טרינידד וטובגו","en":"TRINIDAD AND TOBAGO"},
  {"code":910,"he":"יהודה ושומרון","en":"JUDEA SMARIA"},
  {"code":410,"he":"יוגוסלביה","en":"YUGOSLAVIA"},
  {"code":430,"he":"יוון","en":"GREECE"},
  {"code":160,"he":"יפן","en":"JAPAN"},
  {"code":40,"he":"ירדן","en":"JORDAN"},
  {"code":900,"he":"ישראל","en":"ISRAEL"},
  {"code":51,"he":"כווית","en":"KUWAIT"},
  {"code":64,"he":"כמר א ע מ","en":"KHMER REP"},
  {"code":990,"he":"לא ידוע","en":"UNKNOWN"},
  {"code":0,"he":"לא רשום","en":"UNKNOWN"},
  {"code":8,"he":"לא רשום (בוטל)","en":"UNKNOWN (CA"},
  {"code":124,"he":"לאוס","en":"LAOS"},
  {"code":30,"he":"לבנון","en":"LEBANON"},
  {"code":230,"he":"לוב","en":"LIBYA"},
  {"code":630,"he":"לוכסמבורג","en":"LUXEMBOURG"},
  {"code":302,"he":"לטביה","en":"LATVIA"},
  {"code":209,"he":"ליבריה","en":"LIBERIA"},
  {"code":301,"he":"ליטא","en":"LITHUANIA"},
  {"code":521,"he":"ליכטנשטיין","en":"LIECHTENSTEIN"},
  {"code":272,"he":"לסוטו","en":"LESOTHO"},
  {"code":203,"he":"מאוריטניה","en":"MAURITANIA"},
  {"code":276,"he":"מאוריציוס","en":"MAURITIUS"},
  {"code":212,"he":"מאלי","en":"MALI"},
  {"code":275,"he":"מדגסקר","en":"MADAGASCAR"},
  {"code":262,"he":"מוזמביק","en":"MOZAMBIQUE"},
  {"code":307,"he":"מולדובה","en":"MOLDOVA"},
  {"code":150,"he":"מונגוליה","en":"MONGOLIA"},
  {"code":752,"he":"מונסרת","en":"MONTSERRAT"},
  {"code":641,"he":"מונקו","en":"MONACO"},
  {"code":120,"he":"מיאנמר (בורמה)","en":"MYANMAR (BURMA)"},
  {"code":263,"he":"מלאווי","en":"MALAWI"},
  {"code":117,"he":"מלדיבים","en":"MALADIVES"},
  {"code":127,"he":"מלזיה","en":"MALAYSIA"},
  {"code":673,"he":"מלטה","en":"MALTA"},
  {"code":240,"he":"מצרים","en":"EGYPT"},
  {"code":142,"he":"מקאו","en":"MACAO"},
  {"code":414,"he":"מקדוניה","en":"MACEDONIA"},
  {"code":720,"he":"מקסיקו","en":"MEXICO"},
  {"code":200,"he":"מרוקו","en":"MOROCCO"},
  {"code":202,"he":"מרוקו הספרדית","en":"SPANISH MOROCCO"},
  {"code":756,"he":"מרטיניק","en":"MARTINIQUE"},
  {"code":750,"he":"מרכז אמריקה","en":"CENTRAL AMERICA"},
  {"code":886,"he":"נאורו","en":"NAURU"},
  {"code":570,"he":"נורבגיה","en":"NORWAY"},
  {"code":211,"he":"ניגר","en":"NIGER"},
  {"code":213,"he":"ניגריה","en":"NIGERIA"},
  {"code":870,"he":"ניו זילנד","en":"NEW ZEALAND"},
  {"code":721,"he":"ניקרגואה","en":"NICARAGUA"},
  {"code":274,"he":"נמיביה","en":"NAMIBIA"},
  {"code":114,"he":"נפאל","en":"NEPAL"},
  {"code":245,"he":"סאו טומה ופרינציפה","en":"SAO TOME AND PRINCIP"},
  {"code":241,"he":"סודן","en":"SUDAN"},
  {"code":273,"he":"סווזילנד","en":"SWAZILAND"},
  {"code":252,"he":"סומליה","en":"SOMALIA"},
  {"code":20,"he":"סוריה","en":"SYRIA"},
  {"code":813,"he":"סורינם","en":"SURINAME"},
  {"code":277,"he":"סט הלנה","en":"ST HELENA"},
  {"code":754,"he":"סט וינסנט","en":"ST VINCENT"},
  {"code":755,"he":"סט. לוציה","en":"ST LUCIA"},
  {"code":208,"he":"סיירה ליאונה","en":"SIERRA LEONE"},
  {"code":140,"he":"סין","en":"CHINA"},
  {"code":122,"he":"סינגפור","en":"SINGAPORE"},
  {"code":113,"he":"סיקים","en":"SIKKIM"},
  {"code":411,"he":"סלובניה","en":"SLOVENIA"},
  {"code":532,"he":"סלובקיה","en":"SLOVAKIA"},
  {"code":882,"he":"סמואה","en":"SAMOA"},
  {"code":883,"he":"סמואה המערבית","en":"WESTERN SAMOA"},
  {"code":671,"he":"סן מרינו","en":"SAN MARINO"},
  {"code":204,"he":"סנגל","en":"SENEGAL"},
  {"code":660,"he":"ספרד","en":"SPAIN"},
  {"code":415,"he":"סרביה","en":"SERBIA"},
  {"code":112,"he":"סרי לנקה (צילון)","en":"SRI-LANKA"},
  {"code":80,"he":"עדן","en":"ADEN"},
  {"code":62,"he":"עומן","en":"OMAN"},
  {"code":50,"he":"עירק","en":"IRAQ"},
  {"code":60,"he":"ערב הסעודית","en":"SAUDI ARABIA"},
  {"code":866,"he":"פאפואה","en":"PAPUA"},
  {"code":310,"he":"פולין","en":"POLAND"},
  {"code":889,"he":"פולינזיה הצרפתית","en":"FRENCH POLYNESIA"},
  {"code":711,"he":"פורטו ריקו","en":"PUERTO RICO"},
  {"code":650,"he":"פורטוגל","en":"PORTUGAL"},
  {"code":131,"he":"פיליפינים","en":"PHILIPPINES"},
  {"code":550,"he":"פינלנד","en":"FINLAND"},
  {"code":740,"he":"פנמה","en":"PANAMA"},
  {"code":111,"he":"פקיסטן","en":"PAKISTAN"},
  {"code":831,"he":"פרגוואי","en":"PARAGUAY"},
  {"code":790,"he":"פרו","en":"PERU"},
  {"code":840,"he":"צ'ילה","en":"CHILE"},
  {"code":242,"he":"צאד","en":"CHAD"},
  {"code":530,"he":"צכוסלובקיה","en":"CZECHOSLOVAKIA"},
  {"code":531,"he":"צכיה","en":"CZECH SOCIALIST REP"},
  {"code":640,"he":"צרפת","en":"FRANCE"},
  {"code":730,"he":"קובה","en":"CUBA"},
  {"code":770,"he":"קולומביה","en":"COLOMBIA"},
  {"code":286,"he":"קונגו","en":"CONGO"},
  {"code":723,"he":"קוסטה ריקה","en":"COSTA RICA"},
  {"code":151,"he":"קוריאה","en":"KOREA"},
  {"code":153,"he":"קוריאה הדרומית","en":"S KOREA"},
  {"code":152,"he":"קוריאה הצפונית","en":"N KOREA"},
  {"code":312,"he":"קזחסטאן","en":"KAZAKHSTAN"},
  {"code":63,"he":"קטר","en":"QATAR"},
  {"code":316,"he":"קירג'זסטאן","en":"KIRGHIZSTAN"},
  {"code":862,"he":"קלדוניה החדשה","en":"NEW CALEDONIA"},
  {"code":123,"he":"קמבודיה","en":"CAMBODIA"},
  {"code":244,"he":"קמרון","en":"CAMEROON"},
  {"code":700,"he":"קנדה","en":"CANADA"},
  {"code":253,"he":"קניה","en":"KENYA"},
  {"code":10,"he":"קפריסין","en":"CYPRUS"},
  {"code":412,"he":"קרואטיה","en":"CROATIA"},
  {"code":279,"he":"ראוניון","en":"REUNION"},
  {"code":284,"he":"רואנדה","en":"RWANDA"},
  {"code":260,"he":"רודזיה","en":"RODESIA"},
  {"code":400,"he":"רומניה","en":"ROMANIA"},
  {"code":306,"he":"רוסיה","en":"RUSSIAN FEDERATION"},
  {"code":920,"he":"רמת הגולן","en":"GOLAN HEIGHTS"},
  {"code":243,"he":"רפ מרכז אפריקנית","en":"CENTRAL AFRICA"},
  {"code":930,"he":"רצועת עזה וסיני","en":"GAZA STRIP AND SINAI"},
  {"code":880,"he":"שאר ארצות אוקיאניה","en":"NULL"},
  {"code":690,"he":"שאר ארצות אירופה","en":"OTHER EUROPE"},
  {"code":180,"he":"שאר ארצות אסיה","en":"OTHER ASIAN"},
  {"code":280,"he":"שאר ארצות אפריקה","en":"OTHER AFRICA"},
  {"code":666,"he":"שגוי הסבה","en":"NULL"},
  {"code":560,"he":"שוודיה","en":"SWEDEN"},
  {"code":520,"he":"שוויץ","en":"SWITZERLAND"},
  {"code":121,"he":"תאילנד","en":"THAILAND"},
  {"code":220,"he":"תוניסיה","en":"TUNISIA"},
  {"code":15,"he":"תורכיה","en":"TURKEY"},
  {"code":313,"he":"תורכמניסטאן","en":"TURKMENISTAN"},
  {"code":70,"he":"תימן","en":"YEMEN"},
  {"code":71,"he":"תימן הדמוקרטית","en":"PEOPLE'S DEMO PEP YE"},
];

export const TALMUD_VISA_TYPES: { code: number; label: string }[] = [
  {"code":1,"label":"ב / 1 (תייר עם רשיון עבודה)"},
  {"code":2,"label":"ב / 2 (תייר)"},
  {"code":3,"label":"ב / 1 כללי"},
  {"code":4,"label":"ב / 3"},
  {"code":5,"label":"ב / 2 קבוצתי"},
  {"code":8,"label":"ב / 4 (מתנדב)"},
  {"code":16,"label":"א / 1 (עולה בכוח)"},
  {"code":32,"label":"א / 2 (תלמיד סטודנט)"},
  {"code":64,"label":"א / 3 (איש דת)"},
  {"code":128,"label":"א / 4 (נלווה ל- א/2 או א/3)"},
  {"code":256,"label":"א / 5 (כללי)"},
  {"code":1023,"label":"מעבר"},
  {"code":1535,"label":"אחר"},
  {"code":2047,"label":"עולה"},
  {"code":2559,"label":"קבע"},
  {"code":3071,"label":"חוזר"},
  {"code":3583,"label":"דיפלומט"},
  {"code":3585,"label":"דיפלומט"},
];

export const TALMUD_STUDY_TYPES: { code: number; label: string }[] = [
  {"code":300,"label":"ישיבה גבוהה בנים"},
  {"code":600,"label":"כולל אברכים יום שלם"},
  {"code":605,"label":"כולל אברכים יום שלם"},
  {"code":700,"label":"כולל אברכים חצי יום בוקר"},
  {"code":720,"label":"כולל אברכים חצי יום אחה\"צ"},
  {"code":705,"label":"כולל אברכים חצי יום בוקר"},
  {"code":725,"label":"כולל אברכים חצי יום אחה\"צ"},
  {"code":708,"label":"כולל אברכים חצי יום בוקר בשילוב שירות אזרחי"},
  {"code":728,"label":"כולל אברכים חצי יום אחה\"צ בשילוב שירות אזרחי"},
  {"code":900,"label":"ישיבת הסדר - בנים"},
  {"code":1900,"label":"ישיבת הסדר - בנות"},
  {"code":1000,"label":"כולל האלף - רבנים"},
  {"code":1050,"label":"כולל האלף - דיינים"},
  {"code":1300,"label":"מדרשה לבנות, ישיבה גבוהה בנות"},
  {"code":1400,"label":"מוסד מיוחד לרווקים (בנים ובנות יחד)"},
  {"code":1450,"label":"מוסד מיוחד לנשואים (בנים ובנות יחד)"},
  {"code":1800,"label":"מוסד אקדמאי לרווקים"},
  {"code":1850,"label":"מוסד אקדמאי לנשואים"},
  {"code":7900,"label":"כולל לגמלאים מת\"ל"},
  {"code":706,"label":"כולל בוקר בגרעין תורני"},
  {"code":726,"label":"כולל אחרי הצהריים בגרעין תורני"},
];

/** מצב משפחתי (מילון מושגים). במערכת: בחור = 10 (רווק), נשוי = 20. */
export const TALMUD_MARITAL = { single: 10, married: 20 } as const;

/** סוג מזהה (מילון מושגים): 1 ת"ז, 2 דרכון. */
export const TALMUD_ID_TYPE = { israeli_id: 1, passport: 2 } as const;

/** ישראל - מוצא לכל מי שמזוהה בתעודת זהות. */
export const TALMUD_ISRAEL = 900;
